const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../dist');
const read = file => fs.readFileSync(path.join(root,file),'utf8');
const strip = text => text.match(/<div class="overlay-content">([\s\S]*?)<\/div><\/div>/)?.[1] || '';
const shell = content => read('index.html').replace('<div class="overlay-content">', '<div class="overlay-content">' + content);
const post = '<article class="post-page"><header class="post-header"><h1>Caption test</h1></header><div class="post-content"><p>![[sun.webp]]</p><p>[figcaption: A preserved caption]</p>'+ '<p>Long post content.</p>'.repeat(40) + '</div><a href="/blog/">All writing</a></article>';
(async()=>{
 fs.mkdirSync(path.join(root, '../test-results'), {recursive:true});
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || undefined});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let fail=false;
 const route=async route=>{
  const url=new URL(route.request().url());
  if(url.hostname!=='overlay.test')return route.fulfill({body:''});
  if (/\.(js|css|webp|jpg|svg)$/.test(url.pathname))return route.fulfill({path:path.join(root,url.pathname)});
  if(fail && url.pathname==='/guestbook.html')return route.fulfill({status:503,body:''});
  const body=url.pathname==='/work.html'?strip(read('work.html')):url.pathname==='/about.html'?strip(read('about.html')):url.pathname==='/guestbook.html'?strip(read('guestbook.html')):url.pathname==='/blog/'?'<h1>A piece of my mind.</h1><a href="/blog/2026/08/09/test/">Test post</a>':url.pathname.includes('/blog/')?post:'';
  return route.fulfill({contentType:'text/html',body:shell(body)});
 };
 await page.route('**/*',route);
 await page.goto('http://overlay.test/');
 await page.evaluate(()=>window.savedPlayer=document.querySelector('.spotify-player'));
 await page.screenshot({path:path.join(root,'../test-results/home-preview.png')});
 await page.getByRole('link',{name:'Work',exact:true}).click();
 await page.locator('#project-list').waitFor();
 assert.equal(await page.locator('#project-list a').count(),3);
 assert.equal(await page.locator('#overlay-label').textContent(),'work');
 await page.reload();
 assert.equal(await page.locator('dialog').evaluate(n=>n.open),true);
 await page.locator('.overlay-close').click();
 await page.evaluate(()=>window.savedPlayer=document.querySelector('.spotify-player'));
 await page.getByRole('link',{name:'About',exact:true}).click();
 await page.locator('.about-photo').waitFor();
 assert.equal(await page.locator('#project-list, .about-grid').count(),0);
 assert.equal(await page.locator('dialog').evaluate(n=>n.open),true);
 assert.equal(await page.locator('.home-screen').evaluate(n=>n.inert),true);
 await page.locator('.about-photo').hover();await page.waitForTimeout(500);
 assert.equal(await page.locator('.portrait-caption-tooltip').evaluate(n=>getComputedStyle(n).opacity),'1');
 await page.screenshot({path:path.join(root,'../test-results/about-preview.png')});
 await page.keyboard.press('Escape');
 assert.equal(new URL(page.url()).pathname,'/');
 await page.getByRole('link',{name:'Blog',exact:true}).click();
 await page.getByRole('link',{name:'Test post'}).click();
 await page.locator('.post-figure').waitFor();
 for(let i=0;i<3;i++) {await page.locator('.post-figure').hover();await page.waitForTimeout(500);assert.equal(await page.locator('.post-caption-tooltip').evaluate(n=>getComputedStyle(n).opacity),'1');await page.mouse.move(5,5);}
 await page.locator('.overlay-scroll').evaluate(n=>n.scrollTop=1000);
 assert.equal(await page.evaluate(()=>window.scrollY),0);
 assert.ok(await page.locator('.overlay-scroll').evaluate(n=>n.scrollTop)>0);
 await page.goBack();await page.getByRole('link',{name:'Test post'}).waitFor();
 await page.goForward();await page.locator('.post-figure').waitFor();
 assert.ok(await page.evaluate(()=>window.savedPlayer===document.querySelector('.spotify-player')));
 await page.locator('.overlay-close').click();
 fail=true;await page.getByRole('link',{name:'Guestbook',exact:true}).click();await page.getByRole('alert').waitFor();
 fail=false;await page.getByRole('button',{name:'Try again'}).click();await page.locator('.guestbook-sign').waitFor();
 await page.reload();await page.locator('.guestbook-sign').waitFor();assert.equal(await page.locator('dialog').evaluate(n=>n.open),true);
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 await mobile.route('**/*',route);await mobile.goto('http://overlay.test/about.html');
 assert.ok(await mobile.locator('.about-photo figcaption').isVisible());
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.screenshot({path:path.join(root,'../test-results/mobile-preview.png')});
 await mobile.goto('http://overlay.test/blog/2026/08/09/test/');
 assert.ok(await mobile.locator('.post-figure figcaption').isVisible());
 await mobile.emulateMedia({reducedMotion:'reduce'});
 assert.notEqual(await mobile.locator('.film-grain').evaluate(n=>getComputedStyle(n).animationName),'none');
 assert.deepEqual(errors,[]);
 console.log('PASS: overlays, close/Escape, history, direct links, retry, persistent Spotify iframe, portrait/post captions, isolated scrolling, mobile layout and animation with reduced motion enabled.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
